### Autenticación de un usuario suministrando login y password.
POST  http://127.0.0.1:8081/api/login_user
content-type: application/x-www-form-urlencoded

username=sonia.silverado
&password=s

###
GET http://127.0.0.1:8082/api/series
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE3MzM5MDMxMzYsImV4cCI6MTczMzkxNzUzNn0.Yt4qwOFX5Bhd5gOZuOMOIGpKjnp0jWeaOzl4NGBtOYU